const sharedRules = {
  eqeqeq: "error",
  "no-redeclare": "error",
  "no-undef": "error",
  "no-unreachable": "error",
  "no-unused-vars": ["error", { argsIgnorePattern: "^_", caughtErrors: "none" }],
};

const browserGlobals = {
  AbortController: "readonly",
  atob: "readonly",
  Blob: "readonly",
  btoa: "readonly",
  cancelAnimationFrame: "readonly",
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  crypto: "readonly",
  CustomEvent: "readonly",
  document: "readonly",
  Element: "readonly",
  Event: "readonly",
  fetch: "readonly",
  getComputedStyle: "readonly",
  Headers: "readonly",
  history: "readonly",
  HTMLElement: "readonly",
  Intl: "readonly",
  localStorage: "readonly",
  location: "readonly",
  MutationObserver: "readonly",
  navigator: "readonly",
  Node: "readonly",
  NodeFilter: "readonly",
  performance: "readonly",
  queueMicrotask: "readonly",
  requestAnimationFrame: "readonly",
  Request: "readonly",
  ResizeObserver: "readonly",
  Response: "readonly",
  sessionStorage: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  structuredClone: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
  window: "readonly",
};

const nodeGlobals = {
  AbortSignal: "readonly",
  atob: "readonly",
  btoa: "readonly",
  Buffer: "readonly",
  console: "readonly",
  crypto: "readonly",
  fetch: "readonly",
  process: "readonly",
  Request: "readonly",
  Response: "readonly",
  Headers: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  TextDecoder: "readonly",
  TextEncoder: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
};

export default [
  {
    ignores: ["node_modules/**", "playwright-report/**", "test-results/**", "vendor/**", ".wrangler/**"],
  },
  {
    files: ["src/**/*.js", "dev/**/*.js"],
    languageOptions: { ecmaVersion: "latest", sourceType: "module", globals: browserGlobals },
    rules: sharedRules,
  },
  {
    files: ["**/*.mjs"],
    languageOptions: { ecmaVersion: "latest", sourceType: "module", globals: nodeGlobals },
    rules: sharedRules,
  },
  {
    // Callbacks passed to page.evaluate run in the browser.
    files: ["tests/e2e/**/*.mjs"],
    languageOptions: {
      globals: {
        ...nodeGlobals,
        ClipboardEvent: "readonly",
        DataTransfer: "readonly",
        document: "readonly",
        InputEvent: "readonly",
        localStorage: "readonly",
        location: "readonly",
        window: "readonly",
      },
    },
  },
];
